version: '3.0'
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/config.yaml
    ports:
      - "4317:4317"
    networks: [tracing]

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
    networks: [tracing]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

networks:
  tracing:
